name: CI pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test node app
    runs-on: ubuntu-latest
    steps:
      - name: Check repo code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        # with:
        #   node-version: "24"

      - name: Install Dependencies
        run: npm install

      - name: Run automated tests
        run: npm test
